services:
  rtm_api:
    build:
      context: .           # Це вказує Docker шукати Dockerfile в тій же папці, де лежить цей yaml
      dockerfile: Dockerfile
    container_name: rtm_api_container
    ports:
      - "8080:8080"
    env_file:              # Явно вказуємо Docker підтягнути ваш .env
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PGHOST=${PGHOST}
      - PGPORT=${PGPORT}
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
    networks:
      - rtm_network

networks:
  rtm_network:
    driver: bridge