version: '3.8'

services:
  rtm-web-api:
    image: ghcr.io/plazmatiz/rtm-web-api:latest # Вказуємо образ для pull з GHCR
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rtm_api_container
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PGHOST=db                       # Змінено на ім'я сервісу бази даних
      - PGPORT=5432                     # Внутрішній порт мережі Docker
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
    depends_on:
      db:                               # Виправлено синтаксис (прибрано дефіс)
        condition: service_healthy
    networks:
      - rtm-internal-network

  db:
    image: postgres:17-alpine
    container_name: rtm_db_container
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "127.0.0.1:5433:5432"           # Зовнішній порт 5433, внутрішній 5432
    volumes:
      - rtm_pg_data:/var/lib/postgresql/data # Виправлено назву тома
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER} -d ${PGDATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - rtm-internal-network

networks:
  rtm-internal-network:
    driver: bridge

volumes:
  rtm_pg_data:                          # Назва тома збігається з оголошеною в сервісі db